"""baseline current schema

Revision ID: ef461ad114c5
Revises:
Create Date: 2026-08-13 13:09:17.629774+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef461ad114c5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("api_key_hint", sa.String(length=32), nullable=False),
        sa.Column("api_key_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("models_json", sa.Text(), nullable=False),
        sa.Column("selected_model", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_connections_api_key_fingerprint"),
        "model_connections",
        ["api_key_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_connections_department_id"),
        "model_connections",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_connections_owner_id"), "model_connections", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_connections_provider"), "model_connections", ["provider"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("owner_name", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("skill_id", sa.String(length=128), nullable=False),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("skill_version", sa.String(length=64), nullable=False),
        sa.Column("skill_commit", sa.String(length=64), nullable=False),
        sa.Column("skill_hash", sa.String(length=64), nullable=False),
        sa.Column("manifest_path", sa.Text(), nullable=False),
        sa.Column("manifest_snapshot", sa.Text(), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("worker_pool", sa.String(length=64), nullable=False),
        sa.Column("concurrency_limit", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=False),
        sa.Column("files_json", sa.Text(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("confirmation_required", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_department_id"), "runs", ["department_id"], unique=False)
    op.create_index(op.f("ix_runs_idempotency_key"), "runs", ["idempotency_key"], unique=False)
    op.create_index(op.f("ix_runs_lease_expires_at"), "runs", ["lease_expires_at"], unique=False)
    op.create_index(op.f("ix_runs_owner_id"), "runs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_runs_skill_id"), "runs", ["skill_id"], unique=False)
    op.create_index(op.f("ix_runs_state"), "runs", ["state"], unique=False)
    op.create_index(op.f("ix_runs_worker_id"), "runs", ["worker_id"], unique=False)
    op.create_index(op.f("ix_runs_worker_pool"), "runs", ["worker_pool"], unique=False)
    op.create_table(
        "scheduler_locks",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "service_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("account_encrypted", sa.Text(), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("account_hint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_credentials_department_id"),
        "service_credentials",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_credentials_owner_id"), "service_credentials", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_credentials_service"), "service_credentials", ["service"], unique=False
    )
    op.create_table(
        "workflow_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("owner_name", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("skill_id", sa.String(length=128), nullable=False),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("skill_version", sa.String(length=64), nullable=False),
        sa.Column("model_connection_id", sa.String(length=36), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("reconciliation_dates_json", sa.Text(), nullable=False),
        sa.Column("files_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_batches_department_id"),
        "workflow_batches",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_batches_model_connection_id"),
        "workflow_batches",
        ["model_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_batches_owner_id"), "workflow_batches", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_batches_skill_id"), "workflow_batches", ["skill_id"], unique=False
    )
    op.create_index(op.f("ix_workflow_batches_state"), "workflow_batches", ["state"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("original_name", sa.String(length=512), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_department_id"), "files", ["department_id"], unique=False)
    op.create_index(op.f("ix_files_kind"), "files", ["kind"], unique=False)
    op.create_index(op.f("ix_files_owner_id"), "files", ["owner_id"], unique=False)
    op.create_index(op.f("ix_files_sha256"), "files", ["sha256"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    op.create_table(
        "run_model_audits",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_run_model_audits_connection_id"),
        "run_model_audits",
        ["connection_id"],
        unique=False,
    )
    op.create_table(
        "workflow_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("owner_name", sa.String(length=128), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("skill_id", sa.String(length=128), nullable=False),
        sa.Column("skill_name", sa.String(length=255), nullable=False),
        sa.Column("skill_version", sa.String(length=64), nullable=False),
        sa.Column("skill_hash", sa.String(length=64), nullable=False),
        sa.Column("skill_commit", sa.String(length=64), nullable=False),
        sa.Column("concurrency_limit", sa.Integer(), nullable=False),
        sa.Column("model_connection_id", sa.String(length=36), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("reconciliation_date", sa.String(length=10), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("batch_sequence", sa.Integer(), nullable=False),
        sa.Column("previous_workflow_id", sa.String(length=36), nullable=False),
        sa.Column("context_json", sa.Text(), nullable=False),
        sa.Column("files_json", sa.Text(), nullable=False),
        sa.Column("artifacts_json", sa.Text(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["workflow_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_sessions_batch_id"), "workflow_sessions", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_sessions_department_id"),
        "workflow_sessions",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_sessions_model_connection_id"),
        "workflow_sessions",
        ["model_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_sessions_owner_id"), "workflow_sessions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_sessions_skill_id"), "workflow_sessions", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_sessions_stage"), "workflow_sessions", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_sessions_state"), "workflow_sessions", ["state"], unique=False
    )
    op.create_table(
        "workflow_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_actions_lease_expires_at"),
        "workflow_actions",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(op.f("ix_workflow_actions_name"), "workflow_actions", ["name"], unique=False)
    op.create_index(op.f("ix_workflow_actions_state"), "workflow_actions", ["state"], unique=False)
    op.create_index(
        op.f("ix_workflow_actions_worker_id"), "workflow_actions", ["worker_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_actions_workflow_id"), "workflow_actions", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_messages_workflow_id"), "workflow_messages", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_messages_workflow_id"), table_name="workflow_messages")
    op.drop_table("workflow_messages")
    op.drop_index(op.f("ix_workflow_actions_workflow_id"), table_name="workflow_actions")
    op.drop_index(op.f("ix_workflow_actions_worker_id"), table_name="workflow_actions")
    op.drop_index(op.f("ix_workflow_actions_state"), table_name="workflow_actions")
    op.drop_index(op.f("ix_workflow_actions_name"), table_name="workflow_actions")
    op.drop_index(op.f("ix_workflow_actions_lease_expires_at"), table_name="workflow_actions")
    op.drop_table("workflow_actions")
    op.drop_index(op.f("ix_workflow_sessions_state"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_stage"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_skill_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_owner_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_model_connection_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_department_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_batch_id"), table_name="workflow_sessions")
    op.drop_table("workflow_sessions")
    op.drop_index(op.f("ix_run_model_audits_connection_id"), table_name="run_model_audits")
    op.drop_table("run_model_audits")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_files_sha256"), table_name="files")
    op.drop_index(op.f("ix_files_owner_id"), table_name="files")
    op.drop_index(op.f("ix_files_kind"), table_name="files")
    op.drop_index(op.f("ix_files_department_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_workflow_batches_state"), table_name="workflow_batches")
    op.drop_index(op.f("ix_workflow_batches_skill_id"), table_name="workflow_batches")
    op.drop_index(op.f("ix_workflow_batches_owner_id"), table_name="workflow_batches")
    op.drop_index(op.f("ix_workflow_batches_model_connection_id"), table_name="workflow_batches")
    op.drop_index(op.f("ix_workflow_batches_department_id"), table_name="workflow_batches")
    op.drop_table("workflow_batches")
    op.drop_index(op.f("ix_service_credentials_service"), table_name="service_credentials")
    op.drop_index(op.f("ix_service_credentials_owner_id"), table_name="service_credentials")
    op.drop_index(op.f("ix_service_credentials_department_id"), table_name="service_credentials")
    op.drop_table("service_credentials")
    op.drop_table("scheduler_locks")
    op.drop_index(op.f("ix_runs_worker_pool"), table_name="runs")
    op.drop_index(op.f("ix_runs_worker_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_state"), table_name="runs")
    op.drop_index(op.f("ix_runs_skill_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_owner_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_lease_expires_at"), table_name="runs")
    op.drop_index(op.f("ix_runs_idempotency_key"), table_name="runs")
    op.drop_index(op.f("ix_runs_department_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_model_connections_provider"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_owner_id"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_department_id"), table_name="model_connections")
    op.drop_index(op.f("ix_model_connections_api_key_fingerprint"), table_name="model_connections")
    op.drop_table("model_connections")
    # ### end Alembic commands ###
