'use client';
import {useEffect,useState} from 'react';
type Proposal={id:string;skill_id:string;sha256:string;state:string;validation:string;changes:{path:string;change:string;diff:string;truncated:boolean}[]};
export function PiSkillProposals(){
 const [items,setItems]=useState<Proposal[]>([]);const [allowed,setAllowed]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function refresh(){const r=await fetch('/api/platform/pi-runtime/skill-proposals',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.message??data.detail??'无法读取发布草稿');setItems(data.items??[]);setAllowed(data.can_publish===true)}
 useEffect(()=>{let disposed=false;const load=()=>{if(!disposed)void refresh().catch(e=>{if(!disposed)setError(e.message)})};load();const timer=setInterval(load,10000);return()=>{disposed=true;clearInterval(timer)}},[]);
 async function publish(item:Proposal){setBusy(item.id);setError('');try{const r=await fetch(`/api/platform/pi-runtime/skill-proposals/${encodeURIComponent(item.id)}/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha256:item.sha256})});const data=await r.json();if(!r.ok)throw new Error(data.message??data.detail??'发布失败');await refresh()}catch(e){setError(e instanceof Error?e.message:'发布失败')}finally{setBusy('')}}
 return <section className='space-y-3 rounded-lg border p-4 text-sm' aria-label='Skill 发布确认'><h3 className='font-medium'>Skill 发布确认</h3><p className='text-muted-foreground text-xs'>让 Agent 修改并提交草稿后，在此检查差异并确认发布。已有任务继续使用原版本，新会话使用新版本。</p>{error&&<p role='alert' className='text-destructive'>{error}</p>}{!items.length&&<p className='text-muted-foreground'>暂无发布草稿。</p>}{items.map(item=><details key={item.id} className='rounded border p-3'><summary>{item.skill_id} · {item.state==='published'?'已发布':'待确认'}</summary><p className='my-2 text-xs'>{item.validation}</p>{item.changes.map(change=><details key={change.path} className='my-2'><summary className='break-all text-xs'>{change.change} · {change.path}</summary><pre className='max-h-64 overflow-auto whitespace-pre-wrap break-all text-xs'>{change.diff}</pre>{change.truncated&&<p className='text-destructive text-xs'>差异较长，此处仅显示部分；请先在草稿目录核对完整文件。</p>}</details>)}{item.state==='pending'&&<button disabled={!allowed||Boolean(busy)} onClick={()=>void publish(item)} className='mt-2 rounded border px-3 py-2 disabled:opacity-50'>{busy===item.id?'发布中…':allowed?'确认发布此版本':'需要管理员确认发布'}</button>}</details>)}</section>;
}
